spring:
    application:
        name: gatewayserver
    config:
        import: "optional:configserver:http://localhost:8071/"
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    cloud:
      gateway:
        discovery:
          locator:
            enabled: false
            lowerCaseServiceId: true
        httpclient:
            connect-timeout: 1000
            response-timeout: 2s
      refresh:
          enabled: false

info:
    app:
        name: gatewayserver
        description: "Spring Boot 3 - Microservices: Gateway Server Application"
        version: "1.0.0"

management:
    endpoints:
        web:
            exposure:
                include: "*"
                # include: "refresh"
                # include: "bus-refresh"
    endpoint:
      gateway:
        enabled: true
    info:
        env:
            enabled: true

resilience4j:
  circuitbreaker:
    configs:
        default:
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 2
            failureRateThreshold: 50
            waitDurationInOpenState: 10000
      
logging:
    level:
        com:
            jovisco: debug
